.TH CAE 1
.SH NAME
cae - cae is an editor
.SH SYNOPSIS
.B cae
.I file
.SH DESCRIPTION
.B cae
is a text editor
.SH KEYBINDS
While cae is in heavy development, the best way to understand the keybinds
is to read src/input_handling.cc.

.B "CTRL\-s" - "save current file"

.B "CTRL\-c" - "copy"

.B "CTRL\-v" - "paste"

.B "CTRL\-x" - "cut"

.B "CTRL\-z" - "undo"

.B "CTRL\-r" - "redo"

.B "CTRL\-<mouse-drag>" - "Freely drag the buffer contents"
